Add backup preparation and cleanup scripts for vaultwarden

diff --git a/stacks/m700/vaultwarden/Justfile b/stacks/m700/vaultwarden/Justfile
--- a/stacks/m700/vaultwarden/Justfile
+++ b/stacks/m700/vaultwarden/Justfile
@@ -44,55 +44,49 @@ ls-volume-data export_path:
 ####################################
 
 [group("backup")]
-backup +backup_targets:
+prepare-backup-data:
+    bash prepare_backup_data.sh
+
+[group("backup")]
+cleanup-backup-data:
+    bash cleanup_after_backup.sh
+
+[group("backup")]
+backup +backup_targets: && cleanup-backup-data up
   #!/usr/bin/env bash
   set -euo pipefail
 
   run_id=$(cat /proc/sys/kernel/random/uuid)
+  hc_check_base_name=pocket-id
+  hc_base_url="https://${HC_API}/ping/${HC_PING_KEY}/${hc_check_base_name}"
+  curl_cmd="curl -fsS -m 10 --retry 5 -o /dev/null"
 
-  export_path=${EXPORT_DATA}
-
-  cleanup() {
-    echo "Cleaning up..."
-    status=$?
-    just up || true
-    just _cleanup || true
-    exit "$status"
-  }
-  
-  trap cleanup EXIT
-  hc_check_base_name=vaultwarden
-  do_backup() {
-    for backup_target in {{backup_targets}}; do
-      on_error() {
-        curl -fsS -m 10 --retry 5 -o /dev/null "https://${HC_API}/ping/${HC_PING_KEY}/${hc_check_base_name}-${backup_target}/fail?rid=${run_id}"
-      }
-      trap on_error ERR
-
-      log=$(just restic-backup "$backup_target")
-      exit_code=$?
-      curl -fsS -m 10 --retry 5 -o /dev/null --data-raw "${log}" "https://${HC_API}/ping/${HC_PING_KEY}/${hc_check_base_name}-${backup_target}/${exit_code}?rid=${run_id}"
-
-      log=$(just restic-check "$backup_target")
-      exit_code=$?
-      curl -fsS -m 10 --retry 5 -o /dev/null --data-raw "${log}" "https://${HC_API}/ping/${HC_PING_KEY}/${hc_check_base_name}-${backup_target}/${exit_code}?rid=${run_id}"
-
-      log=$(just restic-forget "$backup_target")
-      exit_code=$?
-      curl -fsS -m 10 --retry 5 -o /dev/null --data-raw "${log}" "https://${HC_API}/ping/${HC_PING_KEY}/${hc_check_base_name}-${backup_target}/${exit_code}?rid=${run_id}"
-    done
-  }
-
-  mkdir -p "$export_path"
-
+  # ping start
   for backup_target in {{backup_targets}}; do
-    curl -fsS -m 10 --retry 5 -o /dev/null "https://${HC_API}/ping/${HC_PING_KEY}/${hc_check_base_name}-${backup_target}/start?create=1&rid=${run_id}"
+    ${curl_cmd} "${hc_base_url}-${backup_target}/start?create=1&rid=${run_id}"
   done
 
-  just export-env vaultwarden "$export_path"
-  just down
-  just export-sqlite "vaultwarden-data" "db.sqlite3" "$export_path"
-  do_backup
+  just prepare-backup-data
+
+  for backup_target in {{backup_targets}}; do
+    # ping fail
+    on_error() {
+      ${curl_cmd} "${hc_base_url}-${backup_target}/fail?rid=${run_id}"
+    }
+    trap on_error ERR
+
+    log=$(just restic-backup "$backup_target")
+    exit_code=$?
+    ${curl_cmd} --data-raw "${log}" "${hc_base_url}-${backup_target}/${exit_code}?rid=${run_id}"
+
+    log=$(just restic-check "$backup_target")
+    exit_code=$?
+    ${curl_cmd} --data-raw "${log}" "${hc_base_url}-${backup_target}/${exit_code}?rid=${run_id}"
+
+    log=$(just restic-forget "$backup_target")
+    exit_code=$?
+    ${curl_cmd} --data-raw "${log}" "${hc_base_url}-${backup_target}/${exit_code}?rid=${run_id}"
+  done
 
 [group("backup")]
 [private]
