Add Invidious backup scripts and configuration files for improved backup management

diff --git a/stacks/m700/invidious/Justfile b/stacks/m700/invidious/Justfile
--- a/stacks/m700/invidious/Justfile
+++ b/stacks/m700/invidious/Justfile
@@ -1,6 +1,181 @@
-help:
-  just --list
+set shell := ["bash", "-eoux", "pipefail", "-c"]
 
-export-subscriptions:
-  # https://docs.invidious.io/api/authenticated-endpoints/#post-apiv1authpreferences
-  curl https://invidious.optimistic.cloud/api/v1/auth/subscriptions
+set dotenv-load
+
+help:
+  just --list --list-submodules
+
+####################################
+######## DOCKER             ########
+####################################
+
+[group('docker')]
+[doc('Start the stack')]
+up:
+  docker compose up -d --remove-orphans
+
+[group('docker')]
+[doc('Stop the stack')]
+down:
+  docker compose down --remove-orphans
+
+[group('docker')]
+[doc('Restart application stack')]
+restart: down && up
+
+[group('docker')]
+[doc('Get logs for the application')]
+logs:
+  docker compose logs -f
+
+[group("docker")]
+[doc('List data of the application')]
+ls-invidious-data:
+  just ls-volume-data invidious-data
+
+[group("docker")]
+[doc('List docker volume data')]
+[private]
+ls-volume-data export_path:
+  docker run --rm -v {{export_path}}:/data:ro alpine ls -la /data
+
+####################################
+######## BACKUP             ########
+####################################
+
+[group("backup")]
+prepare-backup-data:
+    bash prepare_backup_data.sh
+
+[group("backup")]
+cleanup-backup-data:
+  #!/usr/bin/env bash
+  set -eoux pipefail
+
+  export_path="${EXPORT_DATA:?EXPORT_DATA is required}"
+
+  rm -rf "${export_path}"
+
+[group("backup")]
+backup +backup_targets: && cleanup-backup-data up
+  #!/usr/bin/env bash
+  set -euo pipefail
+
+  run_id=$(cat /proc/sys/kernel/random/uuid)
+  hc_check_base_name=invidious
+  hc_base_url="https://${HC_API}/ping/${HC_PING_KEY}/${hc_check_base_name}"
+  curl_cmd="curl -fsS -m 10 --retry 5 -o /dev/null"
+
+  # ping start
+  for backup_target in {{backup_targets}}; do
+    ${curl_cmd} "${hc_base_url}-${backup_target}/start?create=1&rid=${run_id}"
+  done
+
+  just prepare-backup-data
+
+  for backup_target in {{backup_targets}}; do
+    # ping fail
+    on_error() {
+      ${curl_cmd} "${hc_base_url}-${backup_target}/fail?rid=${run_id}"
+    }
+    trap on_error ERR
+
+    log=$(just restic-backup "$backup_target")
+    exit_code=$?
+    ${curl_cmd} --data-raw "${log}" "${hc_base_url}-${backup_target}/${exit_code}?rid=${run_id}"
+
+    log=$(just restic-check "$backup_target")
+    exit_code=$?
+    ${curl_cmd} --data-raw "${log}" "${hc_base_url}-${backup_target}/${exit_code}?rid=${run_id}"
+
+    log=$(just restic-forget "$backup_target")
+    exit_code=$?
+    ${curl_cmd} --data-raw "${log}" "${hc_base_url}-${backup_target}/${exit_code}?rid=${run_id}"
+  done
+
+[group("backup")]
+restore backup_target snapshot_id="latest":
+  #!/usr/bin/env bash
+  mkdir -p "${RESTORE_DATA}"
+  just restic-restore {{backup_target}} {{snapshot_id}}
+
+####################################
+######## RESTIC             ########
+####################################
+
+[group('restic')]
+[doc('Init repository')]
+restic-init backup_target:
+  just _restic-run {{backup_target}} init
+
+[group('restic')]
+[doc('Backup data')]
+[private]
+restic-backup backup_target:
+  #!/usr/bin/env bash
+
+  git_commit=$(git ls-remote https://github.com/optimistic-cloud/home-ops.git HEAD | cut -f1)
+  just _restic-run {{backup_target}} --tag "git_commit=${git_commit}" --exclude-caches --skip-if-unchanged --json --quiet backup /data | jq
+
+[group('restic')]
+[doc('Restore data')]
+[private]
+restic-restore backup_target snapshot_id:
+  just _restic-run {{backup_target}} restore {{snapshot_id}} --target /restore-data
+
+[group('restic')]
+[doc('Get snapshots')]
+restic-snapshots backup_target count="5":
+  just _restic-run {{backup_target}} --quiet snapshots --latest {{count}}
+
+[group('restic')]
+[doc('List files in the latest snapshot')]
+restic-ls backup_target snapshot_id="latest":
+  just _restic-run {{backup_target}} --quiet ls {{snapshot_id}}
+
+[group('restic')]
+[doc('Get stats of the repository')]
+restic-stats backup_target:
+  just _restic-run {{backup_target}} stats --mode raw-data
+
+[group('restic')]
+[doc('Unlock repository')]
+restic-unlock backup_target:
+  just _restic-run {{backup_target}} --quiet unlock
+
+[group('restic')]
+[doc('Forget old snapshots')]
+restic-forget backup_target keep-within="365d":
+  just _restic-run {{backup_target}} --quiet forget --keep-within {{keep-within}}
+
+[group('restic')]
+[doc('Prune snapshots')]
+restic-prune backup_target:
+  just _restic-run {{backup_target}} --quiet prune
+
+[group('restic')]
+[doc('Check snapshots')]
+restic-check backup_target read-data-subset="33%":
+  just _restic-run {{backup_target}} --json check --read-data-subset {{read-data-subset}} | jq
+
+[group('restic')]
+[private]
+[doc('For each restic command but not backup, as it needs additional volumes and environment variables')]
+_restic-run backup_target +restic_args:
+  #!/usr/bin/env nu
+
+  let backup_target = "{{backup_target}}"
+
+  with-env { 
+    HOSTNAME: "m700"
+    RESTIC_ENV_FILE: $"($backup_target).restic.env" 
+  } {
+    ^docker compose -f docker-compose.backup.yaml run --rm restic {{restic_args}}
+  }
+
+[group('utils')]
+[private]
+[doc('Removes temporary files created during backup')]
+_cleanup:
+  rm -rf "${EXPORT_DATA}"
+  rm -rf "${RESTORE_DATA}"
